authors:
  mathiasbrito:
    name: Mathias Santos de Brito
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/16703250?v=4
  ramona:
    name: Elena-Ramona Modroiu
    description: Creator
    avatar: https://commons.wikimedia.org/wiki/File:Male_Avatar.jpg