name: deploy-to-github-pages
run-name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      - test_build
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material
        pip install mkdocs-minify-plugin
        pip install mkdocs-redirects
        pip install mkdocs-git-revision-date-localized-plugin
    - name: Build
      run: |
        mkdocs build --verbose --clean --strict
    - name: Fix permissions
      run: |
        chmod -c -R +rX "site/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done
    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        artifact-name: github-pages
        path: site
    - name: Upload Github Pages artifact
      uses: actions/upload-artifact@v2
